name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Instalacja Dockera
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Budowanie i testowanie Dockera
        run: |
          docker-compose build
          docker-compose run biblioteka pytest
